# spring.application.name=openapi

server:
    port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

